"""Writing the reviewed segmentation in BoneHub's segmentation format (``.seg.nrrd``).

The format is the one ``bonehub_data_schema/segmentation_file.py`` defines, and the one the
dataset's own files are in: voxels hold per-file segment numbers (1, 2, 3 ...; uint8, or
uint16 above 255 segments), and the header maps each number to its BoneHub label and
records the segment's colour and extent. 3D Slicer opens such a file as a segmentation with
one segment per label, named after it.

Nothing here imports Slicer. numpy and SimpleITK are imported on use; both ship with
3D Slicer, so nothing is installed into it.
"""

from __future__ import annotations

from pathlib import Path

from .labels import label_color

SEGMENTATION_SUFFIX = ".seg.nrrd"

#: Segment tags a BoneHub file carries: ``BoneHubLabel:<name>|BoneHubValue:<value>|``.
LABEL_TAG = "BoneHubLabel"
VALUE_TAG = "BoneHubValue"


def segment_number_dtype(number_of_segments: int):
    """The smallest unsigned type that holds segment numbers 1..number_of_segments."""
    import numpy as np

    if number_of_segments <= 255:
        return np.uint8
    if number_of_segments <= 65535:
        return np.uint16
    raise ValueError(f"{number_of_segments} labels in one segmentation; at most 65535 are supported.")


def segment_tags(name: str, value: int) -> str:
    """The tags of a BoneHub segment, in the ``key:value|`` form of a 3D Slicer header."""
    return f"{LABEL_TAG}:{name}|{VALUE_TAG}:{int(value)}|"


def geometry_from_ijk_to_ras(ijk_to_ras) -> tuple:
    """``(origin, spacing, direction)`` of a volume, from 3D Slicer's IJK-to-RAS matrix.

    Slicer works in RAS; files, SimpleITK and the server work in LPS, which flips the first
    two axes. The result is in LPS, with the direction as nine numbers, row by row.
    """
    import numpy as np

    matrix = np.asarray(ijk_to_ras, dtype=float)[:3, :]
    lps = np.diag([-1.0, -1.0, 1.0]) @ matrix
    spacing = np.linalg.norm(lps[:, :3], axis=0)
    direction = lps[:, :3] / spacing
    origin = tuple(float(v) for v in lps[:, 3])
    return origin, tuple(float(v) for v in spacing), tuple(float(v) for v in direction.ravel())


def write_segmentation(numbers, labels: list, geometry: tuple, output_path: Path) -> list:
    """Write segment numbers as a BoneHub segmentation.

    numbers: array in (slice, row, column) order -- that of ``slicer.util.arrayFromVolume``
        and of SimpleITK -- holding 0 for background and n for ``labels[n - 1]``.
    labels: ``(name, BoneLabelMap value)`` of each segment number.
    geometry: ``(origin, spacing, direction)`` of the voxel grid, in LPS; see
        :func:`geometry_from_ijk_to_ras`. The server refuses a mask whose grid is not the
        image's.
    output_path: destination, ending in ``.seg.nrrd``.
    Returns the names of the labels that have voxels; numbers without voxels are left out
    of the header.
    """
    import numpy as np
    import SimpleITK as sitk

    output_path = Path(output_path)
    if not output_path.name.endswith(SEGMENTATION_SUFFIX):
        raise ValueError(f"A BoneHub segmentation file must end in '{SEGMENTATION_SUFFIX}': {output_path}")
    if np.ndim(numbers) != 3:
        raise ValueError(f"A segmentation must be 3D; this one has {np.ndim(numbers)} dimensions.")

    origin, spacing, direction = geometry
    image = sitk.GetImageFromArray(np.asarray(numbers, dtype=segment_number_dtype(len(labels))))
    image.SetOrigin(tuple(origin))
    image.SetSpacing(tuple(spacing))
    image.SetDirection(tuple(direction))

    # 3D Slicer opens a segmentation much faster when the header gives each segment's extent.
    boxes = sitk.LabelShapeStatisticsImageFilter()
    boxes.Execute(image)

    present = []
    for i, number in enumerate(sorted(int(n) for n in boxes.GetLabels())):
        if number > len(labels):
            raise ValueError(f"Segment number {number} has no label; only {len(labels)} were given.")
        name, value = labels[number - 1]
        x, y, z, size_x, size_y, size_z = boxes.GetBoundingBox(number)
        red, green, blue = label_color(value)
        image.SetMetaData(f"Segment{i}_ID", name)
        image.SetMetaData(f"Segment{i}_Name", name)
        image.SetMetaData(f"Segment{i}_NameAutoGenerated", "0")
        image.SetMetaData(f"Segment{i}_Color", f"{red:.6f} {green:.6f} {blue:.6f}")
        image.SetMetaData(f"Segment{i}_ColorAutoGenerated", "0")
        image.SetMetaData(
            f"Segment{i}_Extent", f"{x} {x + size_x - 1} {y} {y + size_y - 1} {z} {z + size_z - 1}"
        )
        image.SetMetaData(f"Segment{i}_LabelValue", str(number))
        image.SetMetaData(f"Segment{i}_Layer", "0")
        image.SetMetaData(f"Segment{i}_Tags", segment_tags(name, value))
        present.append(name)
    image.SetMetaData("Segmentation_MasterRepresentation", "Binary labelmap")
    image.SetMetaData("Segmentation_ContainedRepresentationNames", "Binary labelmap|")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = sitk.ImageFileWriter()
    writer.SetFileName(str(output_path))
    writer.UseCompressionOn()
    writer.Execute(image)
    return present
